version: '3.8'
services:
  app:
    build: .
    ports:
      - ${PORT}:8081
    depends_on:
      - db
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_ENGINE: ${POSTGRES_ENGINE}
      POSTGRES_DB: ${POSTGRES_DB}
      KEY_SECRET: ${KEY_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      DEV: ${DEV}
      IS_ENCRYPT: ${IS_ENCRYPT}
      ENCRYPT_KEY: ${ENCRYPT_KEY}

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - mydbdata:/var/lib/postgresql/data
volumes:
  mydbdata:

